### ISSUE TITLE
Bar Text (numbers) do not show in IE9

### ISSUE THREAD

**Issue by hemant1016** [wpoely86/D3.js-Diverging-Stacked-Bar-Chart#1]
Hello,

First thank you for providing this awesome tool for viewing survey data. The issue is with IE9, where the numerical values do not show up on top of the bars. I'm not using IE9 in compatibility mode. The charts work fine in Chrome and Firefox.

SCRIPT87: Invalid argument. 
d3.min.js, line 3 character 2396

**Comment by wpoely86** [comment]
Hi @hemant1016,

I'm afraid IE9 doesn't play well with D3.js in general. I don't have any computers any more that run IE9, so I cannot test it but this should help: https://github.com/shawnbot/aight
The author of D3.js recommends to use aight for IE8-9. Can you give it a spin?
And what about compatibility mode? Does that fix things?

**Comment by hemant1016** [comment]
Thank you for getting back to me so quick! I could not get it working with aight but I did not spend more than 30 mins on it. Like you said IE9 is not heavily utilized anymore. Therefore I will try to get our organization to upgrade the browsers and focus on D3 vs crappy MS products.
